name: HomeTeleport
version: ${project.version}
main: se.rsrp.hometeleport.Main
api-version: 1.13
author: rosengrenen
website: https://github.com/rosengrenen/HomeTeleport
description: Allow players to teleport to their bed or world spawn.
commands:
  home:
    usage: /home
    permission: hometeleport.home
  hometeleport:
    usage: /hometeleport
    permission: hometeleport.command
permissions:
  hometeleport.reload:
    default: op
    description: Allows reloading the config.
  hometeleport.ignorecooldown:
    default: op
    description: Allows player to ignore the cooldown between teleports.
  hometeleport.command:
    default: op
    description: Allows the usage of the management command /hometeleport.
  hometeleport.commands.home:
    default: true
    description: Allows teleportation to bed/spawn.
